/// <reference types="vite/client" />
interface ImportMetaEnv {
    VITE_HL_CONNECTION_CLUSTER_QUICKNODE: string;
    VITE_HL_CONNECTION_CLUSTER_ANKR: string;
    VITE_HL_NAME_CLUSTER: 'devnet' | 'mainnet-beta';
    VITE_HL_MODE: string;
    VITE_HL_HTO_MINT_KEY: string;
    VITE_HL_USDC_MINT_KEY: string;
    VITE_HL_UPDATE_AUTHORITY_PARCELS: string;
    VITE_HL_UPDATE_AUTHORITY_LOYALTIES: string;
    VITE_HL_UPDATE_AUTHORITY_SOLAMIDS: string;
    VITE_HL_UPDATE_AUTHORITY_ALPHAS: string;
    VITE_HL_UPDATE_AUTHORITY_SOLANAUTS: string;
    VITE_HL_UPDATE_AUTHORITY_PARAGONS: string;
    VITE_HL_UPDATE_AUTHORITY_METACITY: string;
    VITE_HL_UPDATE_AUTHORITY_EXCOMS: string;
    VITE_HL_UPDATE_AUTHORITY_PRIMATES: string;
    VITE_HL_UPDATE_AUTHORITY_ABC: string;
    VITE_HL_UPDATE_AUTHORITY_ANYBODIES: string;
    VITE_HL_UPDATE_AUTHORITY_D0GGIES: string;
    VITE_HL_EXPLORER_URL: string;
    VITE_HL_API_URL: string;
    VITE_HL_AUCTION_HOUSE: string;
    VITE_HL_DEST_WALLET_ADDRESS_FEE: string;
    VITE_HL_PARAGON_PROGRAM_ADDRESS: string;
    VITE_HL_STAKING_PROGRAM_ADDRESS: string;
    VITE_HL_STAKING_REWARD_VAULT: string;
    VITE_HL_STAKING_REWARD_VAULTS: Array<string>;
    VITE_HL_STAKING_BASE_PERIOD: number;
    VITE_HL_STAKING_WALLET: string;
    VITE_HL_STAKING_HTO_TREASURY: string;
    VITE_HL_SWITCHBOARD_FEED_ADDRESS: string;
}
