import { defineNuxtPlugin } from '#app';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

/* import the fontawesome core */
import { library } from '@fortawesome/fontawesome-svg-core';

/* import specific icons */
import {
    faUserCircle,
    faHome,
    faSplit,
    faCirclePlus,
    faSpinnerThird,
    faInfoCircle,
    faCircleMinus,
    faCircleXmark,
    faBars,
    faCircleInfo,
    faCircleCheck,
    faCircleX,
    faCircle,
    faTriangleExclamation,
    faCircleExclamation,
    faSearch,
    faTimes,
    faCopy,
    faArrowDown,
    faAngleLeft,
    faAngleRight,
    faCheck,
    faSpinner,
    faListUl,
    faUserAstronaut,
    faPlus,
    faMinus,
    faChevronDown,
    faRocketLaunch,
    faChevronRight,
    faCircleSmall,
    faUserGroup,
    faLayerGroup,
    faChevronUp,
    faFilterList,
    faGlobe,
    faChevronLeft,
    faArrowUp,
    faSquarePollHorizontal,
    faEmptySet,
    faTimer,
    faImageSlash,
    faUpToDottedLine,
    faArrowsRotate as faArrowsRotateSolid,
    faStamp,
    faChevronsUp,
    faSignature,
    faDownToDottedLine,
    faTrash,
    faUp,
    faDown,
    faTrophy,
    faSackDollar,
    faHeadset,
    faMusic,
    faBan,
    faGun,
    faCar,
    faFlagCheckered,
    faStar,
    faUser,
    faArrowUpRightFromSquare,
    faUserVneck,
} from '@fortawesome/pro-solid-svg-icons';

import {
    faObjectUngroup,
    faLayerGroup as fadLayerGroup,
    faInfoCircle as fadInfoCircle,
    faRectangleVerticalHistory,
    faGrid2,
    faCoinVertical,
    faHistory,
    faList,
    faTags,
    faListTimeline,
    faWallet,
    faArrowUpShortWide,
    faArrowDownShortWide,
    faBracketsCurly,
    faGlobe as fadGlobe,
    faArrowsRepeat,
    faSquarePollHorizontal as fadSquarePollHorizontal,
    faAward,
    faPlusCircle,
    faChartLine,
    faBolt,
    faSquareBolt,
    faEye,
    faArrowsRotate,
    faLayerPlus,
    faCircleDashed as fadCircleDashed,
    faSquareCheck,
    faImages,
    faImage,
    faCheck as fadCheck,
    faShareNodes,
    faListCheck,
    faGripDots,
    faCoin,
    faCalendarDays,
    faMoneyCheckPen,
    faSkull,
    faHourglassHalf,
    faCodeMerge,
} from '@fortawesome/pro-duotone-svg-icons';

/* import specific icons */
import {
    faXmark as farXmark,
    faHome as farHome,
    faStar as farStar,
    faCircleCheck as farCircleCheck,
    faChartLine as farChartLine,
    faCircleInfo as farCircleInfo,
    faCircleExclamation as farCircleExclamation,
    faCircleDashed,
    faTimesCircle,
} from '@fortawesome/pro-regular-svg-icons';

export default defineNuxtPlugin((nuxtApp) => {
    library.add(
        fadCheck,
        faSignature,
        faImages,
        faUp,
        faDown,
        farXmark,
        farCircleInfo,
        faPlusCircle,
        faChartLine,
        faArrowUp,
        faImage,
        faArrowDown,
        faListCheck,
        faGripDots,
        faCoin,
        faArrowsRotateSolid,
        faAngleLeft,
        faAngleRight,
        faSackDollar,
        faList,
        faUserVneck,
        faHistory,
        faGlobe,
        faObjectUngroup,
        faSquareBolt,
        fadCircleDashed,
        faTimesCircle,
        faFilterList,
        faChevronUp,
        fadLayerGroup,
        faCodeMerge,
        faTrophy,
        faCoinVertical,
        faUserGroup,
        farCircleCheck,
        faChevronRight,
        faCircleSmall,
        faHourglassHalf,
        farStar,
        faArrowUpShortWide,
        faRectangleVerticalHistory,
        fadSquarePollHorizontal,
        faGrid2,
        farHome,
        faSpinnerThird,
        faHome,
        faCircleInfo,
        faBars,
        faSplit,
        faTimer,
        faStamp,
        faUserAstronaut,
        faLayerGroup,
        faCirclePlus,
        faInfoCircle,
        faCircleMinus,
        faCircleXmark,
        faShareNodes,
        faTriangleExclamation,
        faCircleExclamation,
        faTrash,
        faCircleCheck,
        faCircleX,
        faSearch,
        faTimes,
        faUpToDottedLine,
        faEye,
        faBolt,
        faCopy,
        faCheck,
        faSpinner,
        faListUl,
        faUserCircle,
        faPlus,
        faCircleDashed,
        faMinus,
        faChevronDown,
        faRocketLaunch,
        farChartLine,
        faTags,
        fadInfoCircle,
        faListTimeline,
        faChevronLeft,
        farChartLine,
        faWallet,
        faArrowDownShortWide,
        faDownToDottedLine,
        faBracketsCurly,
        faLayerPlus,
        fadGlobe,
        faArrowsRotate,
        faArrowsRepeat,
        faSquarePollHorizontal,
        faAward,
        faEmptySet,
        farCircleExclamation,
        faCircle,
        faImageSlash,
        faSquareCheck,
        faChevronsUp,
        faCalendarDays,
        faMoneyCheckPen,
        faHeadset,
        faMusic,
        faBan,
        faSkull,
        faGun,
        faCar,
        faFlagCheckered,
        faStar,
        faUser,
        faArrowUpRightFromSquare
    );

    nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon);
});
